# Generated by Django 3.1.2 on 2020-12-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_management', '0002_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='item',
            field=models.ManyToManyField(to='invoice_management.items'),
        ),
    ]
